name: jobs to build and deploy page
on:
  push:
    branches: [main]

jobs:
  paging_jobs:
    runs-on: ubuntu-latest
    name: build page and deploy
    steps:
      - name: download file
        run: |
          curl -L https://drive.usercontent.google.com/u/0/uc?id=1dg9SV3048uhrpiV90zyh1ysu9QSRRRMV -o voices.zip
          unzip voices.zip -d public/
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: setup nodejs
        run: |
          npm install
      - name: build pages
        run: |
          npm run build
      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "dist"
